# Generated by Django 5.2.5 on 2025-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carne',
            field=models.CharField(default=123456, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
